### ISSUE TITLE
hoist and StateT don't play well

### ISSUE THREAD

**Issue by paolino** [haskell-streaming/streaming#107]
How does hoist work with StateT ?

```haskell
> S.print $ hoist  (flip evalStateT 0) $ S.for (S.each [1..5]) (\x -> get >>= \y -> put x >> S.yield y) 
0
0
0
0
0

> S.print $ hoistUnexposed  (flip evalStateT 0) $ S.for (S.each [1..5]) (\x -> get >>= \y -> put x >> S.yield y) 
0
0
0
0
0

> S.print $ hoist (flip evalStateT 0) $ S.for (S.each [1..5]) (\x -> get >>= \y -> S.yield y >> put x) 
0
0
0
0
0

> S.print $ hoistUnexposed  (flip evalStateT 0) $ S.for (S.each [1..5]) (\x -> get >>= \y -> S.yield y >> put x) 
0
1
2
3
4
```

Not sure this makes any sense, is it so crazy with Pipes ? I don't remember to have suffered this issue before, but I could have been just lucky .

**Comment by treeowl** [comment]
The documentation for `hoist` indicates that the argument must be a monad morphism. `flip evalStateT 0` is not a monoid morphism, so `hoist` is not required to do anything sensible with it. We offer `hoistUnexposed` to hoist general functions. `pipes` may choose to make its `hoist` definition "safe"; we don't.

**Comment by treeowl** [comment]
Specifically, `hoist morph` requires:

```haskell
morph (return x) = return x

morph $ do {x <- m ; f x}
 =  do {x <- morph m ; morph (f x)}
```

But `flip evalStateT 0 (do {x <- m ; f x})` preserves the state between `m` and `f x`, while `do {x <- flip evalStateT 0 m; flip evalStateT 0 (f x)}` does not.

**Comment by paolino** [comment]
Thanks! 
How version 2 does not work and 4 does ? And how am I supposed to think to be sure I always choose version 4 ? They both use unexposed

**Comment by treeowl** [comment]
Neither of those is actually the right way to combine `Stream` with `StateT`. You can use `hoistUnexposed` to think about hoisting something "stepwise". To use `StateT`, you almost certainly want to use `Streaming.distribute`.

```haskell
distribute :: (Monad m, Functor f, MonadTrans t, MFunctor t, Monad (t (Stream f m)))
             => Stream f (t m) r -> t (Stream f m) r
-- distribute :: (Monad m, Functor f) => Stream f (StateT s m) r -> StateT s (Stream f m) r
```

**Comment by paolino** [comment]
Worked perfectly.
```haskell
> S.print $ flip evalStateT 0 $ distribute $ S.for (S.each [1..5]) (\x ->  get >>= \y ->  put x >> S.yield y) 
0
1
2
3
4
> S.print $ flip evalStateT 0 $ distribute $ S.for (S.each [1..5]) (\x ->  get >>= \y ->  S.yield y >> put x) 
0
1
2
3
4
```

Thanks, seems I didn't look enough around

**Comment by treeowl** [comment]
It's not exactly obvious. We should add something like the `Pipes.Lift` module to make this easy.
