### ISSUE TITLE
Eliminate resourcet

### ISSUE THREAD

**Issue by andrewthad** [haskell-streaming/streaming#13]
This library uses `MonadResource` in two places: `readFile` and `writeFile`. It isn't even needed in `writeFile`. In `readFile`, it provides a dangerous opportunity to leak file descriptors since it cannot actually provide prompt finalization for a `Stream`.

In the spirit of `pipes` and `pipes-safe`, I'm going to remove this approach to resource management from `streaming`. If someone would like to create a `streaming-safe` package, that would be a better place to try to handle finalization correctly.

**Comment by ivan-m** [comment]
I actually had [issues](https://github.com/michaelt/streaming-bytestring/issues/17) with the `resourcet` usage with `streaming-bytestring`.

I know in the past I was discouraged by Gabriel to try and use the `-safe` code with another streaming library, suggesting I use `resourcet` instead.

I would like to suggest usage of my `streaming-with` package more as the resource-management idiom for `streaming`.

**Comment by andrewthad** [comment]
Excellent. I’ll make that the recommendation.
