### ISSUE TITLE
Consider dropping support for old GHC versions

### ISSUE THREAD

**Issue by treeowl** [haskell-streaming/streaming#19]
It's fairly annoying to work with pre-AMP versions of `base`. How important is it that we continue to do so?

**Comment by andrewthad** [comment]
I'm in favor of only supporting the last three releases of GHC. So, at this point, anything before 7.10, I could care less about. In practice, I only ever use the most recent two versions of GHC, so I don't even really ever use 7.10.

**Comment by treeowl** [comment]
I didn't even think about the biggest benefit: more expressive types! For example, if the `Monad` constraint on `expand` is weakened to `Functor`, it becomes immediately obvious that it does not duplicate effects.

**Comment by treeowl** [comment]
Argh... That example is potentially problematic because `FreeT` needs an `Applicative` constraint just to get `pure`, but the presence of the (unused!) `<*>` opens up the effect duplication can of worms.

**Comment by andrewthad** [comment]
The `streaming-0.2.0.0` hackage release no longer supports pre-AMP `base`.
