### ISSUE TITLE
Add streaming to Stackage Nightly 

### ISSUE THREAD

**Issue by PierreR** [haskell-streaming/streaming#29]
It would be nice to add `streaming` and its associated packages to stackage nightly.

This would avoid its disappearance from the next LTS release.

Thanks

**Comment by andrewthad** [comment]
I agree. I'll get a new release out soon and get it added.

**Comment by mboes** [comment]
Where are things at these days? Getting `streaming` into Stackage nightly is on the critical path for getting `jvm-streaming` and `sparkle` in as well.

**Comment by andrewthad** [comment]
I just released `streaming-0.2.0.0`. I'll try to get this on stackage nightly soon.

**Comment by chessai** [comment]
streaming is already on stackage! https://www.stackage.org/lts-12.16/package/streaming-0.2.2.0
