### ISSUE TITLE
streaming-0.2.0.0 has no bracketStream

### ISSUE THREAD

**Issue by FintanH** [haskell-streaming/streaming#36]
When upgrading to lts-10.3 for stack I noticed that this came with `streaming-0.2.0.0` and also that `bracketStream` was now eradicated from the library. I couldn't see this change in the `changelog.md`.

Is there a reason this was removed? Is there a different tactic for bracketing a stream?

**Comment by FintanH** [comment]
Ah, I just saw https://github.com/haskell-streaming/streaming/issues/13! I'll close this and look into [`streaming-with`](https://hackage.haskell.org/package/streaming-with-0.2.0.0/docs/Streaming-With.html). :)

**Comment by andrewthad** [comment]
Glad you found that issue. I'd also like to point out that `bracketStream` was pretty unreliable. If you called `bracketStream` and then called `Streaming.Prelude.take` on the resulting stream, your finalizer wouldn't actually get called, which is pretty bad behavior.

**Comment by FintanH** [comment]
Definitely don't want that 😄 Might I propose that this is mentioned in the changelog? :)

**Comment by andrewthad** [comment]
Pushed 206fba61b9c577f55c843e32a813cfb10705ff1d just now.

**Comment by UnkindPartition** [comment]
Sorry, I'm late to this discussion. Was updating some old code of mine, and it no longer builds because of this.

> I'd also like to point out that bracketStream was pretty unreliable. If you called bracketStream and then called Streaming.Prelude.take on the resulting stream, your finalizer wouldn't actually get called, which is pretty bad behavior.

Do you have a concrete example of the finalizer never being called?

It's true that it may not be called as early as you might hope, but it should be called when you run the ResourceT action at the latest (unless you're doing something sinister). Here it's being called despite the `take 1`:

``` haskell
import Streaming
import Streaming.Prelude as S
import Streaming.Internal
import Control.Monad.Trans.Resource

bracketStream :: (Functor f, MonadResource m) =>
       IO a -> (a -> IO ()) -> (a -> Stream f m b) -> Stream f m b
bracketStream alloc free inside = do
        (key, seed) <- lift (allocate alloc free)
        clean key (inside seed)
  where
    clean key = loop where
      loop str = case str of
        Return r -> Effect (release key >> return (Return r))
        Effect m -> Effect (liftM loop m)
        Step f   -> Step (fmap loop f)
{-#INLINABLE bracketStream #-}

my_stream :: Stream (Of Int) (ResourceT IO) ()
my_stream =
  bracketStream (putStrLn "allocated") (\_ -> putStrLn "deallocated")
    (\_ -> S.enumFrom 1)

main = runResourceT $
  S.print $ S.take 1 my_stream
```

**Comment by andrewthad** [comment]
I stepped down from maintaining this library a long time ago. Maybe the current maintainer would be interested in addition it back.
