### ISSUE TITLE
add wrapEffect to the library

### ISSUE THREAD

**Issue by mihaigiurgeanu** [haskell-streaming/streaming#42]
Hi,

Would you consider adding a new function, `wrapEffect`, to the library?

```
-- | before evaluating the monadic action returning the next step in the 'Stream', it
-- extracts the value in a monadic computation @m a@ and passes it to a new monadic
-- computation, @a -> m ()@, that is ran after etracting
wrapEffect :: (Monad m, Functor f) => m a -> (a -> m ()) -> Stream f m r -> Stream f m r
wrapEffect m f = loop
  where loop stream = do
          x <- lift m
          step <- lift $ inspect stream
          lift $ f x
          either return loop' step
        loop' = wrap . fmap loop

```

Of course, the function could be written directly in terms of internals of Streaming library,
using `Stream` constructors - `Return`, `Step`, `Effect` - instead of `inspect` I used above.

This function will allow, for example, making synchronized streams that could be shared
amongst threads, from ordinary streams:

```
-- | transforms a stream into a synchronized stream with the help of a 'MVar'
synchronizeStream :: (MonadIO m) => TMVar a -> (a -> a) -> Stream (Of b) m r -> Stream (Of b) m r
synchronizeStream mvar f = wrapEffect (liftIO $ atomically $ takeTMVar mvar) (liftIO . atomically . putTMVar mvar . f)

-- | a lighter variant of 'synchronizeStream' that makes makes no use of synchronization
-- variable's value
synchronizeStream' :: (MonadIO m) => TMVar a -> Stream (Of b) m r -> Stream (Of b) m r
synchronizeStream' mvar = synchronizeStream mvar identity
```

This could be used to have a stream processed by more concurrent worker threads.

As an example, this is how I use it in my code:

```
mvar  <- liftIO $ newTMVarIO ()
let stream = synchronizeStream' mvar $ fromSocket udpSocket 512
workers <- liftIO $ replicateM 10 $ async (workerThread stream)
liftIO $ sequence_ $ map wait workers
```

where `fromSocket` creates a stream of messages received on an UDP port.

**Comment by chessai** [comment]
I think I like this idea. Note that the function argument needn't be restricted to 'a -> m ()', it could be 'a -> m y', where y is free.

**Comment by chessai** [comment]
Not sure on the name.

**Comment by chessai** [comment]
see PR #72

**Comment by chessai** [comment]
Why was this closed? The PR wasn't merged yet.

**Comment by mihaigiurgeanu** [comment]
My mistake

**Comment by chessai** [comment]
Oh ok. Wasn't sure if it was closed because you didn't like it anymore.

**Comment by chessai** [comment]
Merged now! Thanks!
