### ISSUE TITLE
S.nub referred to in documentation does not exist.

### ISSUE THREAD

**Issue by galenhuntington** [haskell-streaming/streaming#43]
In the example here: https://github.com/haskell-streaming/streaming/blob/9c7e9fa29a4601623074f68193767414d9325a4a/src/Streaming/Prelude.hs#L2484

This function was removed in 855e7251fc1a542bc767eec67ef055bd46d3d7af.  I'm not sure why, as it seems useful, but perhaps there is now another way to do it.  The commit message just refers to an `Alternative` instance, and I don't see how that would help nubbing a stream.

**Comment by treeowl** [comment]
That is very strange indeed. I don't know of any other "built-in" nubbing functionality, and I don't know why this was removed. Do you want to put together a pull request to put it back?

**Comment by galenhuntington** [comment]
Ok.

**Comment by treeowl** [comment]
Also, please take a look at the [nubbing functions](https://github.com/haskell/containers/blob/master/Data/Containers/ListUtils.hs) that will come out in the next version of `containers`. I imagine we want analogues of all of them.

**Comment by treeowl** [comment]
I suggest you use the names from `containers`, and maybe don't bother with a function called `nub`. When nubbing, it's generally best to think about *how* you're doing so.
