### ISSUE TITLE
“slidingWindow 1” is not behaving as expected.

### ISSUE THREAD

**Issue by shlok** [haskell-streaming/streaming#57]
`slidingWindow 1` is not behaving as expected in `streaming-0.2.1.0` (Stack resolver `lts-12.4`). Example:

    $ stack ghci
    ghci> import qualified Streaming.Prelude as S
    ghci> S.print $ S.slidingWindow 1 $ S.each "1234"
    fromList "1"
    fromList "2"
    fromList "23"
    fromList "34"

The expected result is

    fromList "1"
    fromList "2"
    fromList "3"
    fromList "4"

**Comment by treeowl** [comment]
Fixed in #58.
