### ISSUE TITLE
Is there the ability to trace?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-streaming/streaming#60]
Is there a function to do something like

```haskell
trace :: Monad m
      => (t -> Maybe String)
      -> Stream (Of t) m r
      -> Stream (Of t) m r
trace f s = for s $ \i -> do
  maybe (return ()) traceM (f i)
  yield i
```

**Comment by treeowl** [comment]
Good question, but `traceM` is pretty sketchy, so I wouldn't really want to encourage it. Here's the basic building block, I think:

```haskell
track :: (Monad m, Functor f)
      => (forall x. f x -> m y)
      -> Stream f m r
      -> Stream f m r
```

**Comment by tomjaguarpaw** [comment]
What's sketchy about `traceM`?  It's just `traceM string = trace string $ pure ()`.

**Comment by treeowl** [comment]
Right, but that is very rarely something you actually want. You're much more likely to intend something like `liftIO . traceIO`.

**Comment by tomjaguarpaw** [comment]
Turns out I actually want something like `traceM`, which is why I suggested this!  I would like to trace in `Monad`s that don't contain `IO`.

**Comment by treeowl** [comment]
While I accept that it's valid to want that, I oppose its inclusion in this package. It's quite easy to write safe functions that you can slot `traceM` applications into, so I don't see the need for this wild one.

**Comment by tomjaguarpaw** [comment]
> It's quite easy to write safe functions that you can slot traceM applications into, so I don't see the need for this wild one.

I'm not sure what you mean by that.  Could you exaplin?

**Comment by treeowl** [comment]
Consider something like this.

```haskell
trackOf :: Monad m
  => (a -> m y)
  -> Stream (Of a) m r
  -> Stream (Of a) m r
trackOf f = Streaming.Prelude.mapM $ \a -> a <$ f a

trace :: Monad m
      => (t -> Maybe String)
      -> Stream (Of t) m r
      -> Stream (Of t) m r
trace f = trackOf (traverse_ traceM . f)
```

**Comment by tomjaguarpaw** [comment]
`trackOf` would be very nice.  Can we get that?

**Comment by treeowl** [comment]
I just dug through `Streaming.Prelude`, and it turns out we already have it (with a slightly worse type):

```haskell
chain :: Monad m => (a -> m ()) -> Stream (Of a) m r -> Stream (Of a) m r
```

**Comment by tomjaguarpaw** [comment]
That's interesting.  I wonder why it's called `chain`.  Generalizing the
type sounds like a nice idea.

**Comment by treeowl** [comment]
I have absolutely no idea why it's called that. A PR to fix the type signature would be accepted.

**Comment by danidiaz** [comment]
I believe it was named that way to mimic the [corresponding pipes function](http://hackage.haskell.org/package/pipes-4.3.9/docs/Pipes-Prelude.html#v:chain).

**Comment by chessai** [comment]
See PR #68
