### ISSUE TITLE
A way to not repeat the monadic action in derived streams?

### ISSUE THREAD

**Issue by rihardsk** [haskell-streaming/streaming#62]
To illustrate:
```haskell
import Streaming
import qualified Streaming.Prelude as S
import qualified Network.WebSockets as WS

messageId :: MyMessage -> Int
-- we're connecting to some websocket using the `websockets` library
ws :: WS.ClientApp ()
ws connection = do
  S.print . zipSelf . S.map messageId . S.repeatM $ do
    message <- WS.receiveData connection
    return (message :: MyMessage)
    where
      zipSelf s = S.zipWith (,) s s
```
If I ran `ws` it would print out something like
```
(1, 2)
(3, 4)
(5, 6)
...
```
What I actually want is for it to not duplicate calls to `WS.receiveData` and output
```
(1, 1)
(2, 2)
(3, 3)
...
```
Is this at all possible?

In this example one could easily replace the culprit of the issue - `zipSelf` - with a call to `S.map` and be done with it. However the actual code I'm working with is a bit more involved - I've created a bunch of _stream processor_ functions, that somehow transform the original stream, whose results could then as well be fed through some other _stream processors_ or combined and so on. The problem is that each of the derived streams competes for messages from the websocket, fetching them by itself. 

My domain logic is rather easily expressed in the above manner. Rewriting it into a single pass over the original stream doesn't seem feasible. If what I'm asking for isn't possible, is there some other approach to structuring my computations I could use that would make sense here?

**Comment by nickkuk** [comment]
@rihardsk, NB, streaming ecosystem has [streaming-concurrency](https://github.com/haskell-streaming/streaming-concurrency) too.

**Comment by rihardsk** [comment]
@nickkuk, thanks, I didn't know about streaming-concurency. Anyway, it seems I have plenty of options to go by, I'll close the issue.
