### ISSUE TITLE
support window and MonadOfNoReturn

### ISSUE THREAD

**Issue by chessai** [haskell-streaming/streaming#73]
What is the support window for streaming? I would like to drop support for versions of base prior to Applicative-Monad, and change all instances of 'return' in the code to 'pure'.

**Comment by treeowl** [comment]
What's the point?

**Comment by treeowl** [comment]
> Also, there are some places where a 'Monad' constraint could be relaxed into an 'Applicative'

Be careful. We generally aim to make `Stream` a fast simulation of `FreeT`. Some redundant constraints are *intentional* for the sake of compatibility.

**Comment by treeowl** [comment]
> 'return' is a blemish

It is, but we can wait as long as we want to remove it. I generally think support windows should be determined mostly by CPP burden, and the burden here is very low. Once it gets high enough to have a good reason to exclude 7.8, we can surely pull out other compat warts.

**Comment by chessai** [comment]
> Be careful. We generally aim to make Stream a fast simulation of FreeT. Some redundant constraints are intentional for the sake of compatibility.

> It is, but we can wait as long as we want to remove it. I generally think support windows should be determined mostly by CPP burden, and the burden here is very low. Once it gets high enough to have a good reason to exclude 7.8, we can surely pull out other compat warts.

Alright, I think I agree now. Closing.
