### ISSUE TITLE
Unexpected behavior of Streaming.Prelude.head

### ISSUE THREAD

**Issue by jhrcek** [haskell-streaming/streaming#83]
Consider this GHCi session:
```haskell
λ> import qualified Streaming.Prelude as S
λ> :set -XTypeApplications 
λ> S.head $ S.readLn @IO @Int
1<Enter>
2<Enter> -- Why didn't the streaming end here? I'd expect this to return `Just 1 :> ()`
3<Enter>
^CInterrupted.
```

Compare this to behavior of `head_` which behaves as I would expect (ending the streaming after the first successful read):

```haskell
λ> S.head_ $ S.readLn @IO @Int
1
Just 1
```

**Comment by jmcarthur** [comment]
head :: Monad m => Stream (Of a) m r -> m (Of (Maybe a) r)

Note from looking at its type that `Streaming.Prelude.head` returns whatever value the whole stream returns. The only way it can do that is by performing the effects of the entire stream.

**Comment by jhrcek** [comment]
Thanks for the explanation. So this probably means that the current behavior of `head` is what it should be (thought it was a bug) and to get the behavior I was expecting I can probably do something like

````haskell
λ> S.head $ S.take 1 $ S.readLn @IO @Int
1
Just 1 :> ()
```
